feat: faster formatters (#466)
* feat: faster formatters

* chore: `black .`

* fix: missing comma

* fix: missing comma

* chore: `black .`

* fix: ImportError: cannot import name 'compose_left' from 'eth_utils.toolz'

* chore: `black .`

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>